This is makeindex, version 2.16 [MiKTeX 23.5].
Scanning style file ./Projektdokumentation.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Projektdokumentation.acn....done (32 entries accepted, 0 rejected).
Sorting entries....done (157 comparisons).
Generating output file Projektdokumentation.acr....done (49 lines written, 0 warnings).
Output written in Projektdokumentation.acr.
Transcript written in Projektdokumentation.alg.
